---
title: "inovick_OriginalHomeworkCode_03"
output: html_document
---
## Loading the data
```{r}
library("curl")
library("ggplot2")
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall21/zombies.csv")
d <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(d)
summary(d)
#getting the data from github using curl
```

##Challenge 1: Calculate the population mean and standard deviation for each quantitative random variable (height, weight, age, number of zombies killed, and years of education). NOTE: You will not want to use the built in var() and sd() commands as these are for samples. 
```{r}
##Calculating population mean for height, weight, age, number of zombies killed, and years of education
mean(d$height) #67.6301
mean(d$weight) #143.9075
mean(d$age) #20.04696
mean(d$zombies_killed) #2.992
mean(d$years_of_education) #2.996

##Calculating population SD for height, weight, age, number of zombies killed, and years of education
##Found on stack overflow lol
x <- d$height
sdp <- function(x) sqrt(mean((x-mean(x))^2))
sdp(x) #4.30797

x <- d$weight
sdp <- function(x) sqrt(mean((x-mean(x))^2))
sdp(x) #18.39186

x <- d$age
sdp <- function(x) sqrt(mean((x-mean(x))^2))
sdp(x) #2.963583

x <- d$zombies_killed
sdp <- function(x) sqrt(mean((x-mean(x))^2))
sdp(x) #1.747551

x <- d$years_of_education
sdp <- function(x) sqrt(mean((x-mean(x))^2))
sdp(x) #1.675704
```
